name: Build & Deploy NuGet

# doc: https://docs.github.com/en/actions
# variables: https://docs.github.com/en/actions/learn-github-actions/environment-variables
# secrets: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-17

on:
  workflow_run:
    workflows: ["Prepare"]
    types:
      - completed

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: false
        default: 'warning'
    
  
jobs:
      
  build-nuget:
    uses: bnayae/open-workflows/.github/workflows/dotnet-build-deploy-public-nuget.yml@main
    secrets:
      NUGET_PUBLISH: ${{ secrets.NUGET_PUBLISH }}
    with:
      build-config: Release
      dotnet-version: {ci-net-framework}
      include-prerelease: false
 